import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [name, setName] = useState('');

  async function criaAba(){
    await fetch('/api/data', {
        method: 'POST',
        headers: {
          'Accept': 'application/json, text/plain, */*',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: name
        }),
      }).then((res) => {
        if (res.status === 200) {
            console.log("SUCESSO")
        }
        else {
           // erro();
           console.log("error")
        }
    })     
  }

  async function deleteAba(){
    await fetch('/api/data', {
      method: 'DELETE',
      headers: {
        'Accept': 'application/json, text/plain, */*',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name
      }),
    }).then((res) => {
      if (res.status === 200) {
          console.log("DELETADO")
      }
      else {
         // erro();
         console.log("error")
      }
    }) 
  }

  async function updateAba(){
    await fetch('/api/data', {
      method: 'PUT',
      headers: {
        'Accept': 'application/json, text/plain, */*',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name
      }),
    }).then((res) => {
      if (res.status === 200) {
          console.log("ATUALIZADO")
      }
      else {
         // erro();
         console.log("error")
      }
    }) 
  }

  async function getAvaliacao(){
    await fetch('/api/data', {
      method: 'POST',
      headers: {
        'Accept': 'application/json, text/plain, */*',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: name
      }),
    }).then(async(res) => {
      if (res.status === 200) {
          console.log("busca realizada")
          const response = await res.json();

            const data = response?.filter((item) => {
                return item !== null;
            })
          console.log(data)
      }
      else {
         // erro();
         console.log("error")
      }
    }) 
  }
  
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input onChange={(e) => {setName(e.target.value)}} type="text" />
      <button onClick={criaAba}>CRIAR ABA</button>
      <button onClick={deleteAba}>DELETAR ABA</button>
      <button onClick={updateAba}>ATUALIZAR ABA</button>
      <button onClick={getAvaliacao}>GET AVALIACAO</button>
    </div>
  )
}
