import Head from 'next/head'

import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'


import credentials from '../credentials/google_sheets_api.json'

//const  GoogleSpreadsheet  = require('google-spreadsheet');

//import GoogleSpreadsheet from 'google-spreadsheet';


export default function Home() {
  const [name, setName] = useState('');

  function criaAba(){
   
    console.log("Criando " + name);
  }

  function deleteAba(){
    console.log("Deletando " + name);
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input onChange={(e) => {setName(e.target.value)}} type="text" />
      <button onClick={criaAba}>CRIAR ABA</button>
      <button onClick={deleteAba}>DELETAR ABA</button>
    </div>
  )
}
